### ISSUE TITLE
gosr shows an extra highlight '%' at the end of the output

### ISSUE THREAD

**Issue by siddontang** [mattn/go-sixel#14]
Hi, I tried to show the xkcd pic in the terminator with gosr, but I found a highlight '%', is it as expected?

```
wget https://imgs.xkcd.com/comics/barrel_cropped_\(1\).jpg
gosr barrel_cropped_\(1\).jpg
```

![image](https://user-images.githubusercontent.com/1080370/147217262-5ed38141-b203-4aab-9bea-99bd63dc7693.png)

**Comment by mattn** [comment]
It depends on the behavior of the shell you are using.

**Comment by siddontang** [comment]
Got it, I use zsh, and I use bash, the `%` disappeared
