### ISSUE TITLE
broken alpha?

### ISSUE THREAD

**Issue by mattn** [mattn/go-sixel#5]
I'm trying to fix one problem.
![foo](https://cloud.githubusercontent.com/assets/10111/18747674/72ffb4f2-8109-11e6-81e6-884a57d81a58.jpg)

When encode with go-sixel, image has some black pixels 

![](http://go-gyazo.appspot.com/c84d85ec97903945.png)

@saitoha can you figure out cause of this issue?

**Comment by saitoha** [comment]
@mattn 
- Please attach that sixel file.
- Tell me in which terminal you reproduce this problem.

**Comment by mattn** [comment]
[foo.zip](https://github.com/mattn/go-sixel/files/487402/foo.zip)

> Tell me in which terminal you reproduce this problem.

mintty latest.

**Comment by saitoha** [comment]
Reproduced!

Xterm can display it correctly.
<img width="359" alt="2016-09-22 23 16 00" src="https://cloud.githubusercontent.com/assets/1162739/18751841/76a6ac48-811b-11e6-915a-77051665b15c.png">

It's considered mintty specific problem.
The color register \#255 does not work in mintty.

**Comment by saitoha** [comment]
The color register \#255 is treated as 256th color in mintty.
https://github.com/mintty/mintty/blob/master/src/sixel.c#L599

It will cause overflow in https://github.com/mintty/mintty/blob/master/src/sixel.c#L633.

**Comment by saitoha** [comment]
A patch for mintty is available.
https://github.com/saitoha/mintty-sixel/commit/7b6bf811ba617e68a6717cbb5e06cb21470207c6

**Comment by saitoha** [comment]
Merged into upstream.
https://github.com/mintty/mintty/commit/fe48cdcac0c674d142896f600a32d35ff0af1a5b

**Comment by mattn** [comment]
Thanks!
