### ISSUE TITLE
mintty-2.9.5 works only sometimes

### ISSUE THREAD

**Issue by ktye** [mattn/go-sixel#7]
Not sure if this is an issue with go-sixel or rather mintty, or the environment.
`gosr image.png` sometimes works, somtimes it prints text to the terminal.
This is windows 7, mintty-2.9.5 on msys-2 installed and updated today.

Which setup do you use on windows? Have you seen this as well?

**Comment by mattn** [comment]
Can you provide repro steps?

**Comment by ktye** [comment]
It seems to depend on the image content.
I'll investigate myself and come back to you, if I know more.

**Comment by ktye** [comment]
Steps to reproduce (latest versions of go and msys2, with no special setup):
- get go1.11.5.windows-amd64.zip and extract into c:/go
- from msys2.org get: msys2-x86_64-20180531.exe, execute, install to c:/msys64
- pacman -Syu ; then close window and start c:/msys64/msys2.exe
- pacman -Su
- pacman -S git
Mintty version is now 2.9.5

Install go-sixel and two test images:
- export GOPATH=$HOME; # unset GOROOT if there is one
- /c/go/bin/go get github.com/mattn/go-sixel/cmd/gosr
- wget -O im1.png https://avatars0.githubusercontent.com/u/10111
- wget -O im2.png https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png

- **~/bin/gosr im1.png** # repeat 10 times, it always works
- **~/bin/gosr im2.png** # repeat 10 times, it fails about 50%
- **~/bin/gosr im2.png | cat** # this always works!

Repeating last two steps in c:/msys64/mingw64.exe instead of msys2.exe is the same result.
This can be reproduced on 3 machines: 2 different windows 10 and one windows 7

**Comment by mattn** [comment]
Thanks for your explainig. Fixed.
